travis:
  secure:
    BINSTAR_TOKEN: OjmgGaPXRaZix3GTWoavbGpZVM70vdJo5/UQKhXTfNcWKu11MryQyhKjf5yQ5H39Hm984XrlD5VMSLnjrgK0jjWllIXDk3aAquuqmixXOWdLv8oqh5YDbWgPWRnpomMiwyBNDtE+DOKd0d1q+pZCr1kncMS/wetA00iwFFURGmEGB1bU2j7JbFRd1vRkzKS0ri9REqp22JCrzzGX0IMBNAFvfpuKtXdE8uFQ6nQFwvtCiz9D8mdzjBwK2mlLm0U4lTk5f7NZbbeNldj14310vIFpIDKhvNGJouBQRmCUT3knhIi3Gs+BoXcnnulLZ4zjz9ZPlUFGI3i7YLu/al6kVx+2yySteKj2LohLnX18BQFpIZh0gpLFTTaLn8aySpseLteHBWtFim+BLUtjoxUX4IwmdsSWMyTf3iSZNXTSwlktUOzwO8YtB8wpPz9Em4jg8dk6hM41k1pJ+xapbvmL0qQCOKmnYBI2cY3xZ3GSxLqndz6BRiMJ4PvjJdC6p8b3SGgcFfgW4hsOrKkK6oghzQ7Tbntf46BgyzWZQ3hyT/nevJMhz95IDIYDk6WD3dDLQyOHUHAi8ZpZlnGKeTdC63SKOYGraGDLAOVfZWUM5Dtj+7iG7Dmqa+LMTVKpkSpo9wBCutHWfr/hpCyw3X8AdpyTu+MIIrYt2XE5yG9k28w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
