travis:
  secure:
    BINSTAR_TOKEN: CwDOYX7NusiCtZEoDneCPxkHN5r0yaKATGtEU2MXn5YacUle0LGu+FwOXgf+PgTiAuH84MU6D5s77KlbzlWT6M8ZTIvkAQr2FPUv/pWVOtthZQNDUQFfNeak3OgiTU6ogXGOOLgPcUizgkDnxFkaZzNY+0NNRZI765x1tFdk4rkOeCMnMLUcSdO21TQHlMHwHM5+bVfRAIunOoIgDHv3OgmoYFvwkrkxmYwQ8I7J0g5xemI7o7SFksuBGEw6v0WpEjg1BEaAYWF17hff16j52D8ldMRK5vCuTtoO+dXBRXZh9qtFlWB59ltgOCrS0lAkDFqW6xXMHSTABMn16puYSBV636PqX37cHvbqZQBtr4lZyP71XRhIsE0W/cN060ixcRb0gO27zVVmJLBA1yxZ+BSq81JF3Rrfs0eII3cofdDLBEYlPDEQLziOX9mpOLciayOXHWA/WWU0KWYGXOHtUjW14vbG9weA6QqtYNIl/nA3fvnRGvsVefNddcx3/JCNvVPY3v4JLofjREi4ntboIDvSntM4uFBSc4PbKqA87rH8beO4xM3OFUmqu520h1m211LDUKGT8PICS1SGuwcl1FTPMH5fk7omN04Kybwv+3pHzRYah1w4W/MGWPpUOYvPUT2QWnZ6DOAJVQJ6kfN+eerHYtd5n8h7lzeMi9WWBmU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
